#!/usr/bin/env bash
# runs every milestone test suite with the right config.h for each phase
# and prints pass or fail per suite, config.h gets regenerated per phase
# and is left set up for ms1 at the end
set -u
cd "$(dirname "$0")"

PASS=0
FAIL=0

# write_config <extra defines>, writes a config.h with the given macros
write_config() {
  {
    echo "#ifndef __CONFIG_H__"
    echo "#define __CONFIG_H__"
    echo "// generated by run_all_tests.sh"
    for d in "$@"; do
      echo "#define $d"
    done
    cat <<'EOF'
#ifndef MEM_LATENCY
#define MEM_LATENCY 0
#endif
#ifndef BRANCH_PREDICTOR_MODE
#define BRANCH_PREDICTOR_MODE 0
#endif
#if BRANCH_PREDICTOR_MODE != 0
#define PRINT_BRANCH_PREDICTOR_STATS
#endif
#define BRANCH_PREDICTOR_ENTRIES 64
#define TWO_BIT_INITIAL_STATE 0
#endif // __CONFIG_H__
EOF
  } > config.h
}

rebuild() {
  make clean >/dev/null 2>&1
  if ! make >/dev/null 2>&1; then
    echo "BUILD FAILED"
    exit 1
  fi
}

# run_suite <name> <command> <regex of expected output lines>
# a suite passes when nothing is left after filtering the expected lines
run_suite() {
  local name="$1" cmd="$2" filter="$3"
  local out
  out=$(eval "$cmd" 2>&1 | grep -vE "$filter" | grep -v '^[[:space:]]*$')
  if [ -z "$out" ]; then
    echo "PASS: $name"
    PASS=$((PASS + 1))
  else
    echo "FAIL: $name"
    echo "$out" | head -10
    FAIL=$((FAIL + 1))
  fi
}

mkdir -p code/ms1/out/R code/ms1/out/I code/ms1/out/LS \
         code/ms2/out/R code/ms2/out/I code/ms2/out/LS \
         code/ms3/out/LS ms4_tests/out

# ms1
write_config DEBUG_REG_TRACE DEBUG_CYCLE
rebuild
run_suite "MS1 (5 tests)" "bash test_simulator_ms1.sh" '^diff '

# ms2
write_config DEBUG_REG_TRACE DEBUG_CYCLE PRINT_STATS
rebuild
run_suite "MS2 set 1 (6 tests)" "bash test_simulator_ms2.sh" '^diff '

write_config PRINT_STATS
rebuild
run_suite "MS2 extended (vec_xprod stats)" "bash test_simulator_ms2_extended.sh" '^diff '

# ms3
MS3_NOISE='^diff |Please make sure|If it takes more than'
write_config DEBUG_REG_TRACE DEBUG_CYCLE PRINT_STATS "MEM_LATENCY 100" \
             CACHE_ENABLE PRINT_CACHE_STATS PRINT_CACHE_TRACES
rebuild
run_suite "MS3 cache_complete (4 tests)" "bash test_simulator_ms3.sh cache_complete" "$MS3_NOISE"

write_config PRINT_STATS "MEM_LATENCY 100" CACHE_ENABLE PRINT_CACHE_STATS
rebuild
run_suite "MS3 cache_summary (vec_xprod)" "bash test_simulator_ms3.sh cache_summary" "$MS3_NOISE"

write_config PRINT_STATS "MEM_LATENCY 100" PRINT_CACHE_STATS
rebuild
run_suite "MS3 no_cache (vec_xprod)" "bash test_simulator_ms3.sh no_cache" "$MS3_NOISE"

# ms4, these scripts rebuild themselves with make MS4=1 so config.h
# just needs the defaults
write_config DEBUG_REG_TRACE DEBUG_CYCLE
if bash ms4_tests/test_all_ms4.sh >/dev/null 2>&1; then
  echo "PASS: MS4 (icache x2 + 1-bit BP + 2-bit BP)"
  PASS=$((PASS + 1))
else
  echo "FAIL: MS4 (rerun ./ms4_tests/test_all_ms4.sh for details)"
  FAIL=$((FAIL + 1))
fi
if ./ms4_tests/terminal_gui.sh --check >/dev/null 2>&1; then
  echo "PASS: MS4 terminal GUI self-check"
  PASS=$((PASS + 1))
else
  echo "FAIL: MS4 terminal GUI self-check"
  FAIL=$((FAIL + 1))
fi

# put the ms1 build back
write_config DEBUG_REG_TRACE DEBUG_CYCLE
make clean >/dev/null 2>&1 && make >/dev/null 2>&1

echo
echo "==============================="
echo "  $PASS suites passed, $FAIL failed"
echo "==============================="
exit $((FAIL > 0))
